# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 首页  - 孟令杰的官方网站 # ex. I m Jie
name: 纯洁的微笑 # ex. DONGChuan
email: agcto@126.com
location: beijing,china # ex. Nice, France
company: 10T免费资源
company_url: http://www.agcto.com/share/2017/10/01/resource-sharing.html
github_url: https://github.com/agcto # ex. https://github.com/DONGChuan
cnblog_url: http://www.cnblogs.com/agcto
description: the world is colorful

favicon: favicon.png # Image must be in assets/images
repository: agcto/agcto.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://www.agcto.com
enforce_ssl: www.agcto.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /spring-boot
    label: Spring-Boot
  -
    href: /spring-cloud
    label: Spring-Cloud

#  -
#    href: /open-source
#    label: Open-Source

  -
    href: /blog
    label: Archives

  -
    href: /link
    label: Links
    
  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: agcto
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: agcto
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: agcto
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true